# ---
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: odoo-stg-web
#   labels:
#     type: local
# spec:
#   storageClassName: manual
#   capacity:
#     storage: 5Gi
#   accessModes:
#     - ReadWriteOnce
#   hostPath:
#     path: "/data/volumes/odoo-stg-web"
#   nodeAffinity:
#     required:
#       nodeSelectorTerms:
#       - matchExpressions:
#         - key: kubernetes.io/hostname
#           operator: In
#           values:
#           - tambun-worker2
# ---
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: odoo-stg-addons
#   labels:
#     type: local
# spec:
#   storageClassName: manual
#   capacity:
#     storage: 5Gi
#   accessModes:
#     - ReadWriteOnce
#   hostPath:
#     path: "/data/volumes/odoo-stg-addons"
#   nodeAffinity:
#     required:
#       nodeSelectorTerms:
#       - matchExpressions:
#         - key: kubernetes.io/hostname
#           operator: In
#           values:
#           - tambun-worker2
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: odoo-stg-web-claim
#   namespace: odoo-flux
# spec:
#   volumeName: odoo-stg-web
#   storageClassName: manual
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 5Gi
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: odoo-stg-addons-claim
#   namespace: odoo-flux
# spec:
#   volumeName: odoo-stg-addons
#   storageClassName: manual
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 5Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: odoo-flux-web-claim
  namespace: odoo-flux
spec:
  storageClassName: nfs-cluster-client
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: odoo-flux-addons-claim
  namespace: odoo-flux
spec:
  storageClassName: nfs-cluster-client
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi