---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: odoo
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: odoo
  policy:
    semver:
      range: '>1.0.0-rc <2.0.0-rc'

