apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: odoo--policy
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: odoo'
  policy:
    semver:
      range: 16-v2.0.x
